In [18]:
import pandas as pd
import numpy as np
import os

In [19]:
#working_directory = r"/Users/stephanemasyn/Desktop/FinTech/Homeworks/PROJECTS/Project2"
#os.chdir(working_directory)
#print(os.getcwd())

## Create Training Set

In [20]:
# Using pandas as pd to read the data for the time period of 2015 to 2020.

#nfl2021off = pd.read_csv('./resources/NFL2021OFF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
#       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
#       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
#       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
#       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
#       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
#nfl2021off['Year'] = '2021'

nfl2020off = pd.read_csv('./resources/NFL2020OFF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2020off['Year'] = '2020'

nfl2019off = pd.read_csv('./resources/NFL2019OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2019off['Year'] = '2019'

nfl2018off = pd.read_csv('./resources/NFL2018OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2018off['Year'] = '2018'

nfl2017off = pd.read_csv('./resources/NFL2017OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2017off['Year'] = '2017'

nfl2016off = pd.read_csv('./resources/NFL2016OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2016off['Year'] = '2016'

nfl2015off = pd.read_csv('./resources/NFL2015OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2015off['Year'] = '2015'

In [21]:
# Preview the first five lines of the nfl2015off dataframe
nfl2015off.head()

,D,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
0,NaN,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Tot Yds & TO,Tot Yds & TO.1,Tot Yds & TO.2,Unnamed: 8,...,Rushing.2,Rushing.3,Rushing.4,Penalties,Penalties.1,Penalties.2,Unnamed: 25,Unnamed: 26,Unnamed: 27,2015
1,0.0,Rk,Tm,G,PF,Yds,Ply,Y/P,TO,FL,...,TD,Y/A,1stD,Pen,Yds,1stPy,Sc%,TO%,EXP,2015
2,1.0,1,Carolina Panthers,16,500,5871,1060,5.5,19,9,...,19,4.3,136,103,887,24,42.9,9.6,114.88,2015
3,2.0,2,Arizona Cardinals,16,489,6533,1041,6.3,24,11,...,16,4.2,92,94,758,44,42.5,11.8,148.43,2015
4,3.0,3,New England Patriots,16,465,5991,1050,5.7,14,7,...,14,3.7,87,96,860,31,43.2,5.7,138.04,2015

In [22]:
# Remove row 0 and 1 
nfl2015off = nfl2015off.drop([0,1])
nfl2016off = nfl2016off.drop([0,1])
nfl2017off = nfl2017off.drop([0,1])
nfl2018off = nfl2018off.drop([0,1])
nfl2019off = nfl2019off.drop([0,1])

In [23]:
# Remove column D for years 2015 through 2019
nfl2015o = nfl2015off.drop(columns=['D']).head()
nfl2016o = nfl2016off.drop(columns=['D']).head()
nfl2017o = nfl2017off.drop(columns=['D']).head()
nfl2018o = nfl2018off.drop(columns=['D']).head()
nfl2019o = nfl2019off.drop(columns=['D']).head()

In [24]:
#  Preview the first five lines of the nfl2019 dataframe
nfl2019o.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Baltimore Ravens,16,531,6521,1064,6.1,15,7,386,...,21,5.5,188,109,867,27,52.1,8.6,245.99,2019
3,2,San Francisco 49ers,16,479,6097,1012,6,23,10,336,...,23,4.6,110,105,939,31,44.3,12,123.17,2019
4,3,Tampa Bay Buccaneers,16,458,6366,1086,5.9,41,11,353,...,15,3.7,81,133,1111,28,38.3,20.7,44,2019
5,4,New Orleans Saints,16,458,5982,1011,5.9,8,2,347,...,12,4.3,97,120,1036,20,47,4.2,167.04,2019
6,5,Kansas City Chiefs,16,451,6067,976,6.2,15,10,350,...,16,4.2,93,107,1029,46,49.4,8,217.32,2019

In [25]:
# For consistency make nfl 2020o = nfl2020off 
nfl2020o = nfl2020off

In [27]:
# Preview the first five lines of the nfl2020 dataframe
nfl2020o.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Green Bay Packers,16,509,6224,990,6.3,11,6,358,...,16,4.8,114,84,684,28,49.7,5.6,290.75,2020
3,2,Buffalo Bills,16,501,6343,1034,6.1,22,11,397,...,16,4.2,119,102,941,38,49.4,11.8,228.66,2020
4,3,Tampa Bay Buccaneers,16,492,6145,1017,6.0,17,5,364,...,16,4.1,82,84,715,44,47.8,8.9,246.24,2020
5,4,Tennessee Titans,16,491,6343,1031,6.2,12,5,381,...,26,5.2,142,86,783,36,47.9,7.2,245.01,2020
6,5,New Orleans Saints,16,482,6023,1045,5.8,17,9,367,...,30,4.6,147,98,1005,21,45.5,9.0,176.94,2020

In [30]:
# Merge response data together
data_frames = [nfl2020o[0:32], nfl2019o[0:32], nfl2018o[0:32], nfl2017o[0:32], nfl2016o[0:32], nfl2015o[0:32]]
o_total = pd.concat(data_frames)

In [31]:
# Cast the year variable as int
o_total['Year'] = o_total['Year'].astype('int')

In [33]:
# Preview the first and last five lines of the o_total dataframe
display(o_total.head())
display(o_total.tail())

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Green Bay Packers,16,509,6224,990,6.3,11,6,358,...,16,4.8,114,84,684,28,49.7,5.6,290.75,2020
3,2,Buffalo Bills,16,501,6343,1034,6.1,22,11,397,...,16,4.2,119,102,941,38,49.4,11.8,228.66,2020
4,3,Tampa Bay Buccaneers,16,492,6145,1017,6.0,17,5,364,...,16,4.1,82,84,715,44,47.8,8.9,246.24,2020
5,4,Tennessee Titans,16,491,6343,1031,6.2,12,5,381,...,26,5.2,142,86,783,36,47.9,7.2,245.01,2020
6,5,New Orleans Saints,16,482,6023,1045,5.8,17,9,367,...,30,4.6,147,98,1005,21,45.5,9.0,176.94,2020

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Carolina Panthers,16,500,5871,1060,5.5,19,9,357,...,19,4.3,136,103,887,24,42.9,9.6,114.88,2015
3,2,Arizona Cardinals,16,489,6533,1041,6.3,24,11,373,...,16,4.2,92,94,758,44,42.5,11.8,148.43,2015
4,3,New England Patriots,16,465,5991,1050,5.7,14,7,348,...,14,3.7,87,96,860,31,43.2,5.7,138.04,2015
5,4,Seattle Seahawks,16,423,6058,1035,5.9,16,8,335,...,10,4.5,128,117,1007,17,42,8.6,129.31,2015
6,5,Pittsburgh Steelers,16,423,6327,1011,6.3,28,7,331,...,16,4.4,91,94,868,33,40.5,13.7,22.98,2015

In [35]:
#NFL2021DEF = pd.read_csv('./resources/NFL2021DEF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
#       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
#       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
#       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
#       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
#       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
#NFL2021DEF['Year'] = '2021'

nfl2020def = pd.read_csv('./resources/NFL2020DEF.csv', names=['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2020def['Year'] = '2020'

nfl2019def = pd.read_csv('./resources/NFL2019DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2019def['Year'] = '2019'

nfl2018def = pd.read_csv('./resources/NFL2018DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2018def['Year'] = '2018'

nfl2017def = pd.read_csv('./resources/NFL2017DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2017def['Year'] = '2017'

nfl2016def = pd.read_csv('./resources/NFL2016DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2016def['Year'] = '2016'

nfl2015def = pd.read_csv('./resources/NFL2015DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2015def['Year'] = '2015'

In [36]:
# Remove row 0 and 1 
nfl2015def = nfl2015def.drop([0,1])
nfl2016def = nfl2016def.drop([0,1])
nfl2017def = nfl2017def.drop([0,1])
nfl2018def = nfl2018def.drop([0,1])
nfl2019def = nfl2019def.drop([0,1])
nfl2020def = nfl2020def.drop([0,1])
#nfl202def = nfl2021def.drop([0,1])

In [38]:
# Preview the first five lines of the nfl2015def dataframe
nfl2015def.he16	277	4668	947	4.9	23	9	...	10	3.6	71	94	795	27	29.3	13.2	59.08	2015
3	2.0	2	Cincinnati Bengals	16ad()

,D,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1.0,1,Seattle Seahawks,16,277,4668,947,4.9,23,9,...,10,3.6,71,94,795,27,29.3,13.2,59.08,2015
3,2.0,2,Cincinnati Bengals,16,279,5453,1032,5.3,28,7,...,8,4.3,74,116,1063,31,28.9,15,40.96,2015
4,3.0,3,Kansas City Chiefs,16,287,5269,1037,5.1,29,7,...,7,4.1,86,110,941,34,27.3,15.3,105.76,2015
5,4.0,4,Denver Broncos,16,296,4530,1033,4.4,27,13,...,10,3.3,81,104,773,46,26.9,11.9,141.86,2015
6,5.0,5,Minnesota Vikings,16,302,5510,1015,5.4,22,9,...,7,4.3,94,109,875,35,33.3,11.9,11.53,2015

In [43]:
# Remove column D for years 2015 through 2019
nfl2015d = nfl2015def.drop(columns=['D']).head()
nfl2016d = nfl2016def.drop(columns=['D']).head()
nfl2017d = nfl2017def.drop(columns=['D']).head()
nfl2018d = nfl2018def.drop(columns=['D']).head()
nfl2019d = nfl2019def.drop(columns=['D']).head()

In [44]:
# For consistency make nfl 2020d = nfl2020def
nfl2020d = nfl2020def

In [45]:
nfl2017d

,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1,Minnesota Vikings,16,252,4415,956,4.6,19,5,260,...,10,3.7,59,105,928,33,27.9,10.1,145.07,2017
3,2,Jacksonville Jaguars,16,268,4578,993,4.6,33,12,257,...,9,4.3,91,112,1050,23,23.9,15.6,252.15,2017
4,3,Los Angeles Chargers,16,272,5254,997,5.3,27,9,282,...,11,4.9,99,109,996,30,28.5,15.1,120.25,2017
5,4,Philadelphia Eagles,16,295,4904,976,5,31,12,272,...,7,3.8,62,101,917,33,27.1,15.4,162.09,2017
6,5,New England Patriots,16,296,5856,1022,5.7,18,6,325,...,6,4.7,98,111,1035,23,30.2,9.9,12.09,2017

In [ ]:
# Merge response data together
data_frames_2 = [ NFL2020D[0:32], NFL2019D[0:32], NFL2018D[0:32], NFL2017D[0:32], NFL2016D[0:32], NFL2015D[0:32]]
#NFL2021DEF[0:32],
D_total = pd.concat(data_frames_2)

In [ ]:
D_total

In [ ]:
#D_total.columns = ['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
#       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
 #      'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
 #      'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
  #     'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
  #     'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year']

D_total['Year'] = O_total['Year'].astype('int')

In [ ]:
D_total.tail()

In [ ]:
trainSet = O_total.merge(D_total, on = ['Team', 'Year'])

## Create Test Set

In [ ]:
pd.set_option('display.max_columns', 500)

NFL2021OFF = pd.read_csv('./resources/NFL2021OFF.csv')
NFL2021OFF['Year'] = '2021'

NFL2021DEF = pd.read_csv('./resources/NFL2021DEF.csv')
NFL2021DEF['Year'] = '2021'

NFL2021OFF = NFL2021OFF[1:33]
NFL2021OFF.columns = ['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year']

NFL2021DEF = NFL2021DEF[1:33]
NFL2021DEF.columns = ['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year']

testSet = NFL2021OFF.merge(NFL2021DEF, on = ['Team', 'Year'])
testSet.head()

In [ ]:
adjusted_columns = ['O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_TO', 'O_Fumbles_Lost', 'O_1st_D',
       'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards', 'O_R_TD',
       'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 'O_Pe_1st_D',
       'O_Scoring_Drives', 'O_Expected_Points', 
       'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards', 'D_Plays',
       'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Attempts', 'D_P_Yards', 'D_P_TD', 'D_P_Int',
       'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards', 'D_R_TD', 
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Pe_1st_D', 'D_Scoring_Drives',
       'D_Expected_Points']

for col in [adjusted_columns]:
    testSet[col] = testSet[col].astype('float')

testSet['O_Games_Played'] = testSet['O_Games_Played'].astype('int')
adjuster = 16 / testSet['O_Games_Played'] 

testSet[adjusted_columns] = testSet[adjusted_columns].mul(adjuster, axis = 0)
testSet.head()

In [ ]:
testSet.to_csv('./resources/TestSet3.csv', index = False)

In [ ]:
testSet['Year'] = testSet['Year'].astype('int')


mydata = pd.concat([testSet, trainSet])

In [ ]:
mydata.head()

In [ ]:
columns = ['O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost', 'O_1st_D',
       'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards', 'O_R_TD',
       'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 'O_Pe_1st_D',
       'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 
       'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards', 'D_Plays',
       'D_Y/Play', 'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Attempts', 'D_P_Yards', 'D_P_TD', 'D_P_Int', 'D_P_Y/PA',
       'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards', 'D_R_TD', 'D_R_Y/A',
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Pe_1st_D', 'D_Scoring_Drives',
       'D_TD_%', 'D_Expected_Points']

for col in [columns]:
    mydata[col] = mydata[col].astype('float')

## Append Superbowl Winners

In [ ]:
mydata['Superbowl'] = 0

In [ ]:
SBwinners = pd.read_csv('./resources/SuperbowlWinners.csv')
SBwinners.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
SBwinners.head()

In [ ]:
SBwinners.Date = pd.to_datetime(SBwinners.Date)

In [ ]:
SBwinners['Year'] = pd.DatetimeIndex(SBwinners['Date']).year
SBwinners = SBwinners[['Year', 'Winner']]
SBwinners.tail()

In [ ]:
SBwinners['Year'] = SBwinners['Year'] - 1
SBwinners.Year = SBwinners.Year.astype('object')
SBwinners['Superbowl'] = 1

In [ ]:
SBwinners.Year = SBwinners.Year.astype('int')
mydata.Year = mydata.Year.astype('int')

test = pd.merge(mydata, SBwinners, left_on = ['Year','Team'], right_on = ['Year', 'Winner'], how = 'left')
test.head()

In [ ]:
test.drop(['Superbowl_x', 'Winner'], axis=1, inplace = True)

In [ ]:
pd.set_option('display.max_rows', 500)
test.Superbowl_y = test.Superbowl_y.fillna(0)
test.Superbowl_y = test.Superbowl_y.astype('int')
test.rename(columns = {'Superbowl_y': 'Superbowl'}, inplace = True)

In [ ]:
test.dtypes
test.Superbowl.sum()

## Modeling

In [ ]:
import pylab as pl
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [ ]:
test.head()

In [ ]:
#split into values for test and train
test.O_Rank = test.O_Rank.astype('int')
test.D_Rank = test.D_Rank.astype('int')

train_columns = ['O_Rank', 'O_Points_For', 'O_Total_Yards',
       'O_Y/Play', 'O_TO', 'O_1st_D',
       'O_P_Completions', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Yards', 'O_R_TD',
       'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 
       'O_Scoring_Drives', 'D_Rank',
       'D_Points_Allowed', 'D_Total_Yards', 
       'D_Y/Play', 'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Yards', 'D_P_TD', 'D_P_Int', 'D_P_Y/PA',
       'D_P_Passing_1st_D', 'D_R_Yards', 'D_R_TD', 'D_R_Y/A',
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Scoring_Drives']


X = np.asarray(test[train_columns])
y = np.asarray(test['Superbowl'])
print(X.shape)
print(y.shape)

In [ ]:
#normalize
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [ ]:
teams = test.loc[ :31 , 'Team']

O_rank = test.loc[0:31, 'O_Rank']
D_rank = test.loc[0:31, 'D_Rank']

X_test = X[0:32]
X_train = X[32:]

y_test = y[0:32]
y_train = y[32:]

print(X_test.shape)
print(y_test.shape)
print(X_train.shape)
print(y_train.shape)

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [ ]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

In [ ]:
yhat = LR.predict(X_test)
yhat

In [ ]:
yhat_binary = LR.predict(X_train)
print("Accuracy:",metrics.accuracy_score(y_train, yhat_binary))

In [ ]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

np.vstack((y_train, yhat_binary)).T

In [ ]:
df = pd.DataFrame({'Team':teams, 'Prediction':yhat}) 
df

In [ ]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

In [ ]:
df2 = pd.DataFrame({'Team':teams, 'Prediction':yhat_prob[:,1], 'O_Rank':O_rank, 'D_rank':D_rank }) 
df2

In [ ]:
df2 = df2.sort_values(by = ['Prediction'], ascending = False)
df2['Prediction_Rank'] = df2['Prediction'].rank(ascending = False)

df2

## ADABOOST

In [ ]:
# Load libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.ensemble import AdaBoostClassifier

# Import Support Vector Classifier
from sklearn.svm import SVC
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [ ]:
svc=SVC(probability=True, kernel='linear')

# Create adaboost classifer object
ada =AdaBoostClassifier(n_estimators=20, base_estimator=svc,learning_rate=1)

#abc = AdaBoostClassifier(n_estimators=30, learning_rate=1)

# Train Adaboost Classifer
model = ada.fit(X_train, y_train)

In [ ]:
#Predict the response for test dataset
y_pred_binary = model.predict(X_train)
y_pred = model.predict_proba(X_test)
y_pred

In [ ]:
df3 = pd.DataFrame({'Team':teams, 'Prediction':y_pred[:,1], 'O_Rank':O_rank, 'D_rank':D_rank }) 
df3['Prediction_Rank'] = df3['Prediction'].rank(ascending = False)
df3 = df3.sort_values(by = ['Prediction'], ascending = False)
df3

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_train, y_pred_binary))