In [ ]:
# importing dependencies
import pandas as pd
import numpy as np
import os

In [2]:
#working_directory = r"/Users/stephanemasyn/Desktop/FinTech/Homeworks/PROJECTS/Project2"
#os.chdir(working_directory)
#print(os.getcwd())

## Create Training Set

In [3]:
# Using pandas as pd to read the data for the time period of 2015 to 2020.

#nfl2021off = pd.read_csv('./resources/NFL2021OFF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
#       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
#       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
#       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
#       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
#       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
#nfl2021off['Year'] = '2021'

nfl2020off = pd.read_csv('./resources/NFL2020OFF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2020off['Year'] = '2020'

nfl2019off = pd.read_csv('./resources/NFL2019OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2019off['Year'] = '2019'

nfl2018off = pd.read_csv('./resources/NFL2018OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2018off['Year'] = '2018'

nfl2017off = pd.read_csv('./resources/NFL2017OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2017off['Year'] = '2017'

nfl2016off = pd.read_csv('./resources/NFL2016OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2016off['Year'] = '2016'

nfl2015off = pd.read_csv('./resources/NFL2015OFF.csv', names=['D','O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
nfl2015off['Year'] = '2015'

In [4]:
# Preview the first five lines of the nfl2015off dataframe
nfl2015off.head()

,D,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
0,NaN,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Tot Yds & TO,Tot Yds & TO.1,Tot Yds & TO.2,Unnamed: 8,...,Rushing.2,Rushing.3,Rushing.4,Penalties,Penalties.1,Penalties.2,Unnamed: 25,Unnamed: 26,Unnamed: 27,2015
1,0.0,Rk,Tm,G,PF,Yds,Ply,Y/P,TO,FL,...,TD,Y/A,1stD,Pen,Yds,1stPy,Sc%,TO%,EXP,2015
2,1.0,1,Carolina Panthers,16,500,5871,1060,5.5,19,9,...,19,4.3,136,103,887,24,42.9,9.6,114.88,2015
3,2.0,2,Arizona Cardinals,16,489,6533,1041,6.3,24,11,...,16,4.2,92,94,758,44,42.5,11.8,148.43,2015
4,3.0,3,New England Patriots,16,465,5991,1050,5.7,14,7,...,14,3.7,87,96,860,31,43.2,5.7,138.04,2015

In [5]:
# Remove row 0 and 1 
nfl2015off = nfl2015off.drop([0,1])
nfl2016off = nfl2016off.drop([0,1])
nfl2017off = nfl2017off.drop([0,1])
nfl2018off = nfl2018off.drop([0,1])
nfl2019off = nfl2019off.drop([0,1])
nfl2020off = nfl2020off.drop([0,1])

In [6]:
# Remove column D for years 2015 through 2019
nfl2015o = nfl2015off.drop(columns=['D']).head()
nfl2016o = nfl2016off.drop(columns=['D']).head()
nfl2017o = nfl2017off.drop(columns=['D']).head()
nfl2018o = nfl2018off.drop(columns=['D']).head()
nfl2019o = nfl2019off.drop(columns=['D']).head()

In [7]:
#  Preview the first five lines of the nfl2019 dataframe
nfl2019o.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Baltimore Ravens,16,531,6521,1064,6.1,15,7,386,...,21,5.5,188,109,867,27,52.1,8.6,245.99,2019
3,2,San Francisco 49ers,16,479,6097,1012,6,23,10,336,...,23,4.6,110,105,939,31,44.3,12,123.17,2019
4,3,Tampa Bay Buccaneers,16,458,6366,1086,5.9,41,11,353,...,15,3.7,81,133,1111,28,38.3,20.7,44,2019
5,4,New Orleans Saints,16,458,5982,1011,5.9,8,2,347,...,12,4.3,97,120,1036,20,47,4.2,167.04,2019
6,5,Kansas City Chiefs,16,451,6067,976,6.2,15,10,350,...,16,4.2,93,107,1029,46,49.4,8,217.32,2019

In [8]:
# For consistency make nfl 2020o = nfl2020off 
nfl2020o = nfl2020off

In [9]:
# Preview the first five lines of the nfl2020 dataframe
nfl2020o.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Green Bay Packers,16,509,6224,990,6.3,11,6,358,...,16,4.8,114,84,684,28,49.7,5.6,290.75,2020
3,2,Buffalo Bills,16,501,6343,1034,6.1,22,11,397,...,16,4.2,119,102,941,38,49.4,11.8,228.66,2020
4,3,Tampa Bay Buccaneers,16,492,6145,1017,6.0,17,5,364,...,16,4.1,82,84,715,44,47.8,8.9,246.24,2020
5,4,Tennessee Titans,16,491,6343,1031,6.2,12,5,381,...,26,5.2,142,86,783,36,47.9,7.2,245.01,2020
6,5,New Orleans Saints,16,482,6023,1045,5.8,17,9,367,...,30,4.6,147,98,1005,21,45.5,9.0,176.94,2020

In [10]:
# Merge response data together
nfl_o_merge = [nfl2020o[0:32], nfl2019o[0:32], nfl2018o[0:32], nfl2017o[0:32], nfl2016o[0:32], nfl2015o[0:32]]

o_total = pd.concat(nfl_o_merge)

In [11]:
# Cast the year variable as int
o_total['Year'] = o_total['Year'].astype('int')

In [12]:
# Preview the first and last five lines of the o_total dataframe

display(o_total.head())
display(o_total.tail())

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Green Bay Packers,16,509,6224,990,6.3,11,6,358,...,16,4.8,114,84,684,28,49.7,5.6,290.75,2020
3,2,Buffalo Bills,16,501,6343,1034,6.1,22,11,397,...,16,4.2,119,102,941,38,49.4,11.8,228.66,2020
4,3,Tampa Bay Buccaneers,16,492,6145,1017,6.0,17,5,364,...,16,4.1,82,84,715,44,47.8,8.9,246.24,2020
5,4,Tennessee Titans,16,491,6343,1031,6.2,12,5,381,...,26,5.2,142,86,783,36,47.9,7.2,245.01,2020
6,5,New Orleans Saints,16,482,6023,1045,5.8,17,9,367,...,30,4.6,147,98,1005,21,45.5,9.0,176.94,2020

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year
2,1,Carolina Panthers,16,500,5871,1060,5.5,19,9,357,...,19,4.3,136,103,887,24,42.9,9.6,114.88,2015
3,2,Arizona Cardinals,16,489,6533,1041,6.3,24,11,373,...,16,4.2,92,94,758,44,42.5,11.8,148.43,2015
4,3,New England Patriots,16,465,5991,1050,5.7,14,7,348,...,14,3.7,87,96,860,31,43.2,5.7,138.04,2015
5,4,Seattle Seahawks,16,423,6058,1035,5.9,16,8,335,...,10,4.5,128,117,1007,17,42,8.6,129.31,2015
6,5,Pittsburgh Steelers,16,423,6327,1011,6.3,28,7,331,...,16,4.4,91,94,868,33,40.5,13.7,22.98,2015

In [13]:
#NFL2021DEF = pd.read_csv('./resources/NFL2021DEF.csv', names=['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
#       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
#       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
#       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
#       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
#       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year'] )
#NFL2021DEF['Year'] = '2021'

nfl2020def = pd.read_csv('./resources/NFL2020DEF.csv', names=['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2020def['Year'] = '2020'

nfl2019def = pd.read_csv('./resources/NFL2019DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2019def['Year'] = '2019'

nfl2018def = pd.read_csv('./resources/NFL2018DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2018def['Year'] = '2018'

nfl2017def = pd.read_csv('./resources/NFL2017DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2017def['Year'] = '2017'

nfl2016def = pd.read_csv('./resources/NFL2016DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2016def['Year'] = '2016'

nfl2015def = pd.read_csv('./resources/NFL2015DEF.csv', names=['D','D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year'] )
nfl2015def['Year'] = '2015'

In [14]:
# Remove row 0 and 1 
nfl2015def = nfl2015def.drop([0,1])
nfl2016def = nfl2016def.drop([0,1])
nfl2017def = nfl2017def.drop([0,1])
nfl2018def = nfl2018def.drop([0,1])
nfl2019def = nfl2019def.drop([0,1])
nfl2020def = nfl2020def.drop([0,1])
#nfl202def = nfl2021def.drop([0,1])

In [15]:
# Preview the first five lines of the nfl2015def dataframe
nfl2015def.head()

,D,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1.0,1,Seattle Seahawks,16,277,4668,947,4.9,23,9,...,10,3.6,71,94,795,27,29.3,13.2,59.08,2015
3,2.0,2,Cincinnati Bengals,16,279,5453,1032,5.3,28,7,...,8,4.3,74,116,1063,31,28.9,15,40.96,2015
4,3.0,3,Kansas City Chiefs,16,287,5269,1037,5.1,29,7,...,7,4.1,86,110,941,34,27.3,15.3,105.76,2015
5,4.0,4,Denver Broncos,16,296,4530,1033,4.4,27,13,...,10,3.3,81,104,773,46,26.9,11.9,141.86,2015
6,5.0,5,Minnesota Vikings,16,302,5510,1015,5.4,22,9,...,7,4.3,94,109,875,35,33.3,11.9,11.53,2015

In [16]:
# Remove column D for years 2015 through 2019
nfl2015d = nfl2015def.drop(columns=['D']).head()
nfl2016d = nfl2016def.drop(columns=['D']).head()
nfl2017d = nfl2017def.drop(columns=['D']).head()
nfl2018d = nfl2018def.drop(columns=['D']).head()
nfl2019d = nfl2019def.drop(columns=['D']).head()

In [17]:
# For consistency make nfl 2020d = nfl2020def
nfl2020d = nfl2020def

In [18]:
# Preview the first five lines of the nfl2015def dataframe
nfl2015d

,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1,Seattle Seahawks,16,277,4668,947,4.9,23,9,273,...,10,3.6,71,94,795,27,29.3,13.2,59.08,2015
3,2,Cincinnati Bengals,16,279,5453,1032,5.3,28,7,307,...,8,4.3,74,116,1063,31,28.9,15,40.96,2015
4,3,Kansas City Chiefs,16,287,5269,1037,5.1,29,7,313,...,7,4.1,86,110,941,34,27.3,15.3,105.76,2015
5,4,Denver Broncos,16,296,4530,1033,4.4,27,13,289,...,10,3.3,81,104,773,46,26.9,11.9,141.86,2015
6,5,Minnesota Vikings,16,302,5510,1015,5.4,22,9,318,...,7,4.3,94,109,875,35,33.3,11.9,11.53,2015

In [19]:
# Merge response data together
nfl_d_merge = [nfl2020d[0:32], nfl2019d[0:32], nfl2018d[0:32], nfl2017d[0:32], nfl2016d[0:32], nfl2015d[0:32]]

#nfl2021d[0:32],
d_total = pd.concat(nfl_d_merge)

In [20]:
d_total.head()

,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1,Los Angeles Rams,16,296,4511,989,4.6,22,8,280,...,12,3.8,91,78,582,19,27.9,12.0,85.89,2020
3,2,Baltimore Ravens,16,303,5276,1017,5.2,22,12,347,...,12,4.6,96,77,646,38,30.0,12.4,-17.69,2020
4,3,Pittsburgh Steelers,16,312,4893,996,4.9,27,9,281,...,13,4.3,94,103,980,24,29.3,13.8,33.24,2020
5,4,Washington Football Team,16,329,4873,1004,4.9,23,7,289,...,14,4.2,100,85,708,28,31.4,12.2,32.51,2020
6,5,New Orleans Saints,16,337,4974,992,5.0,26,8,320,...,11,3.9,85,64,517,50,34.7,13.1,-40.02,2020

In [21]:
# Cast the year variable as int

#d_total.columns = ['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
#       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
 #      'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
 #      'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
  #     'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
  #     'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year']

d_total['Year'] = d_total['Year'].astype('int')

In [22]:
display(d_total.head())
display(d_total.tail())

,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1,Los Angeles Rams,16,296,4511,989,4.6,22,8,280,...,12,3.8,91,78,582,19,27.9,12.0,85.89,2020
3,2,Baltimore Ravens,16,303,5276,1017,5.2,22,12,347,...,12,4.6,96,77,646,38,30.0,12.4,-17.69,2020
4,3,Pittsburgh Steelers,16,312,4893,996,4.9,27,9,281,...,13,4.3,94,103,980,24,29.3,13.8,33.24,2020
5,4,Washington Football Team,16,329,4873,1004,4.9,23,7,289,...,14,4.2,100,85,708,28,31.4,12.2,32.51,2020
6,5,New Orleans Saints,16,337,4974,992,5.0,26,8,320,...,11,3.9,85,64,517,50,34.7,13.1,-40.02,2020

,D_Rank,Team,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,...,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Year
2,1,Seattle Seahawks,16,277,4668,947,4.9,23,9,273,...,10,3.6,71,94,795,27,29.3,13.2,59.08,2015
3,2,Cincinnati Bengals,16,279,5453,1032,5.3,28,7,307,...,8,4.3,74,116,1063,31,28.9,15,40.96,2015
4,3,Kansas City Chiefs,16,287,5269,1037,5.1,29,7,313,...,7,4.1,86,110,941,34,27.3,15.3,105.76,2015
5,4,Denver Broncos,16,296,4530,1033,4.4,27,13,289,...,10,3.3,81,104,773,46,26.9,11.9,141.86,2015
6,5,Minnesota Vikings,16,302,5510,1015,5.4,22,9,318,...,7,4.3,94,109,875,35,33.3,11.9,11.53,2015

In [23]:
trainset = o_total.merge(d_total, on = ['Team', 'Year'])
trainset.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,...,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points
0,1,Green Bay Packers,16,509,6224,990,6.3,11,6,358,...,1805,16,4.5,119,79,734,29,39.9,11.4,-109.67
1,2,Buffalo Bills,16,501,6343,1034,6.1,22,11,397,...,1914,21,4.6,125,86,728,27,39.4,15.3,-123.10
2,3,Tampa Bay Buccaneers,16,492,6145,1017,6.0,17,5,364,...,1289,10,3.6,78,95,1015,26,33.7,14.0,-22.04
3,4,Tennessee Titans,16,491,6343,1031,6.2,12,5,381,...,1933,18,4.5,113,103,840,31,45.2,13.3,-185.20
4,5,New Orleans Saints,16,482,6023,1045,5.8,17,9,367,...,1502,11,3.9,85,64,517,50,34.7,13.1,-40.02

## Create Test Set

In [24]:
pd.set_option('display.max_columns', 500)

nfl2021off = pd.read_csv('./resources/NFL2021OFF.csv')
nfl2021off['Year'] = '2021'

nfl2021def = pd.read_csv('./resources/NFL2021DEF.csv')
nfl2021def['Year'] = '2021'

nfl2021off = nfl2021off[1:33]
nfl2021off.columns = ['O_Rank', 'Team', 'O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost',
       'O_1st_D', 'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD',
       'O_P_Int', 'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards',
       'O_R_TD', 'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards',
       'O_Pe_1st_D', 'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 'Year']

nfl2021def = nfl2021def[1:33]
nfl2021def.columns = ['D_Rank', 'Team', 'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards',
       'D_Plays', 'D_Y/Play', 'D_TD', 'D_Fumbles_Lost',
       'D_1st_D', 'D_P_Completions', 'D_P_Attempts', 'D_P_Yards', 'D_P_TD',
       'D_P_Int', 'D_P_Y/PA', 'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards',
       'D_R_TD', 'D_R_Y/A', 'D_R_1st_D', 'D_Pe', 'D_Pe_Yards',
       'D_Pe_1st_D', 'D_Scoring_Drives', 'D_TD_%', 'D_Expected_Points', 'Year']

testset = nfl2021off.merge(nfl2021def, on = ['Team', 'Year'])
testset.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points
0,1,Dallas Cowboys,16,479,6444,1092,5.9,20,9,368,422,619,4496,35,11,6.9,235,441,1948,13,4.4,102,122,1059,31,41.8,10.4,129.5,2021,7,16,332,5652,1012,5.6,33,8,305,344,578,3883,22,25,6.3,180,396,1769,12,4.5,90,118,943,35,31.6,17.1,31.06
1,2,Tampa Bay Buccaneers,16,470,6492,1079,6,19,7,383,463,692,4905,40,12,6.9,258,365,1587,16,4.3,100,95,864,25,43.4,10.4,194.61,2021,10,16,336,5318,1022,5.2,27,11,326,416,637,3855,24,16,5.7,204,340,1463,11,4.3,88,78,625,34,34.1,14.5,-25.01
2,3,Buffalo Bills,16,456,6069,1064,5.7,22,6,373,390,609,4030,34,16,6.3,221,428,2039,19,4.8,127,109,940,25,45.9,12.2,142.89,2021,2,16,279,4584,968,4.7,30,11,281,290,510,2766,11,19,5.1,135,425,1818,19,4.3,107,98,817,39,28.9,15.6,55.21
3,4,Kansas City Chiefs,16,452,6356,1060,6,25,12,391,421,631,4536,35,13,6.9,248,402,1820,16,4.5,113,106,880,30,48.1,14.4,183.83,2021,13,16,340,5908,1006,5.9,28,13,345,388,585,4100,27,15,6.7,200,391,1808,12,4.6,113,110,866,32,36.6,16.1,-95.51
4,5,Cincinnati Bengals,16,444,5963,995,6,21,7,326,369,526,4300,35,14,7.5,204,418,1663,16,4,90,68,588,32,43.6,10.5,119.1,2021,18,16,355,5588,1009,5.5,19,7,315,403,602,4051,24,12,6.3,205,366,1537,14,4.2,92,112,900,18,34.3,10.7,-27.17

In [59]:
adjusted_columns = ['O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_TO', 'O_Fumbles_Lost', 'O_1st_D',
       'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards', 'O_R_TD',
       'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 'O_Pe_1st_D',
       'O_Scoring_Drives', 'O_Expected_Points', 
       'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards', 'D_Plays',
       'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Attempts', 'D_P_Yards', 'D_P_TD', 'D_P_Int',
       'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards', 'D_R_TD', 
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Pe_1st_D', 'D_Scoring_Drives',
       'D_Expected_Points']

for col in [adjusted_columns]:
    testset[col] = testset[col].astype('float')

testset['O_Games_Played'] = testset['O_Games_Played'].astype('int')
adjuster = 16 / testset['O_Games_Played'] 

testset[adjusted_columns] = testset[adjusted_columns].mul(adjuster, axis = 0)
display(testset.head())
display(testset.tail())

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points
0,1,Dallas Cowboys,16,479.0,6444.0,1092.0,5.9,20.0,9.0,368.0,422.0,619.0,4496.0,35.0,11.0,6.9,235.0,441.0,1948.0,13.0,4.4,102.0,122.0,1059.0,31.0,41.8,10.4,129.50,2021,7,16.0,332.0,5652.0,1012.0,5.6,33.0,8.0,305.0,344.0,578.0,3883.0,22.0,25.0,6.3,180.0,396.0,1769.0,12.0,4.5,90.0,118.0,943.0,35.0,31.6,17.1,31.06
1,2,Tampa Bay Buccaneers,16,470.0,6492.0,1079.0,6,19.0,7.0,383.0,463.0,692.0,4905.0,40.0,12.0,6.9,258.0,365.0,1587.0,16.0,4.3,100.0,95.0,864.0,25.0,43.4,10.4,194.61,2021,10,16.0,336.0,5318.0,1022.0,5.2,27.0,11.0,326.0,416.0,637.0,3855.0,24.0,16.0,5.7,204.0,340.0,1463.0,11.0,4.3,88.0,78.0,625.0,34.0,34.1,14.5,-25.01
2,3,Buffalo Bills,16,456.0,6069.0,1064.0,5.7,22.0,6.0,373.0,390.0,609.0,4030.0,34.0,16.0,6.3,221.0,428.0,2039.0,19.0,4.8,127.0,109.0,940.0,25.0,45.9,12.2,142.89,2021,2,16.0,279.0,4584.0,968.0,4.7,30.0,11.0,281.0,290.0,510.0,2766.0,11.0,19.0,5.1,135.0,425.0,1818.0,19.0,4.3,107.0,98.0,817.0,39.0,28.9,15.6,55.21
3,4,Kansas City Chiefs,16,452.0,6356.0,1060.0,6,25.0,12.0,391.0,421.0,631.0,4536.0,35.0,13.0,6.9,248.0,402.0,1820.0,16.0,4.5,113.0,106.0,880.0,30.0,48.1,14.4,183.83,2021,13,16.0,340.0,5908.0,1006.0,5.9,28.0,13.0,345.0,388.0,585.0,4100.0,27.0,15.0,6.7,200.0,391.0,1808.0,12.0,4.6,113.0,110.0,866.0,32.0,36.6,16.1,-95.51
4,5,Cincinnati Bengals,16,444.0,5963.0,995.0,6,21.0,7.0,326.0,369.0,526.0,4300.0,35.0,14.0,7.5,204.0,418.0,1663.0,16.0,4,90.0,68.0,588.0,32.0,43.6,10.5,119.10,2021,18,16.0,355.0,5588.0,1009.0,5.5,19.0,7.0,315.0,403.0,602.0,4051.0,24.0,12.0,6.3,205.0,366.0,1537.0,14.0,4.2,92.0,112.0,900.0,18.0,34.3,10.7,-27.17

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points
27,28,Detroit Lions,16,288.0,5080.0,997.0,5.1,23.0,9.0,310.0,374.0,561.0,3293.0,20.0,14.0,5.5,181.0,401.0,1787.0,11.0,4.5,97.0,103.0,809.0,32.0,32.3,13.8,-9.87,2021,30,16.0,437.0,6078.0,1026.0,5.9,16.0,7.0,350.0,335.0,509.0,3904.0,28.0,9.0,7.3,196.0,491.0,2174.0,18.0,4.4,129.0,87.0,818.0,25.0,47.9,9.5,-169.54
28,29,Carolina Panthers,16,287.0,4764.0,1035.0,4.6,27.0,7.0,304.0,319.0,556.0,3032.0,12.0,20.0,5,164.0,429.0,1732.0,17.0,4,112.0,106.0,854.0,28.0,29.5,14.8,-81.37,2021,19,16.0,363.0,4792.0,968.0,5,16.0,7.0,290.0,308.0,476.0,2942.0,23.0,9.0,5.7,155.0,454.0,1850.0,14.0,4.1,106.0,106.0,886.0,29.0,36.2,8.6,11.19
29,30,Houston Texans,16,255.0,4374.0,954.0,4.6,22.0,7.0,248.0,331.0,513.0,3016.0,18.0,15.0,5.4,151.0,399.0,1358.0,8.0,3.4,70.0,110.0,913.0,27.0,25.8,11.8,-87.37,2021,27,16.0,424.0,6130.0,1036.0,5.9,25.0,8.0,359.0,340.0,514.0,3836.0,23.0,17.0,7,202.0,491.0,2294.0,25.0,4.7,129.0,84.0,748.0,28.0,43.0,12.8,-121.57
30,31,New York Giants,16,251.0,4707.0,991.0,4.7,27.0,9.0,289.0,336.0,562.0,3113.0,14.0,18.0,5.2,167.0,394.0,1594.0,8.0,4,86.0,85.0,653.0,36.0,28.7,15.2,-79.15,2021,23,16.0,394.0,5707.0,1079.0,5.3,22.0,7.0,349.0,393.0,593.0,3740.0,27.0,15.0,6,212.0,455.0,1967.0,14.0,4.3,114.0,104.0,785.0,23.0,41.4,12.6,-76.60
31,32,Jacksonville Jaguars,16,227.0,4873.0,964.0,5.1,29.0,12.0,285.0,338.0,572.0,3219.0,10.0,17.0,5.3,167.0,361.0,1654.0,13.0,4.6,86.0,98.0,807.0,32.0,24.4,16.7,-50.20,2021,31,16.0,446.0,5769.0,1015.0,5.7,7.0,1.0,338.0,360.0,514.0,3736.0,23.0,6.0,6.9,190.0,475.0,2033.0,22.0,4.3,120.0,100.0,827.0,28.0,46.6,4.3,-167.01

In [60]:
testset.to_csv('./resources/TestSet3.csv', index = False)

In [61]:
testset['Year'] = testset['Year'].astype('int')

mydata = pd.concat([testset, trainset])

In [28]:
mydata.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points
0,1,Dallas Cowboys,16,479.0,6444.0,1092.0,5.9,20.0,9.0,368.0,422.0,619.0,4496.0,35.0,11.0,6.9,235.0,441.0,1948.0,13.0,4.4,102.0,122.0,1059.0,31.0,41.8,10.4,129.5,2021,7,16.0,332.0,5652.0,1012.0,5.6,33.0,8.0,305.0,344.0,578.0,3883.0,22.0,25.0,6.3,180.0,396.0,1769.0,12.0,4.5,90.0,118.0,943.0,35.0,31.6,17.1,31.06
1,2,Tampa Bay Buccaneers,16,470.0,6492.0,1079.0,6,19.0,7.0,383.0,463.0,692.0,4905.0,40.0,12.0,6.9,258.0,365.0,1587.0,16.0,4.3,100.0,95.0,864.0,25.0,43.4,10.4,194.61,2021,10,16.0,336.0,5318.0,1022.0,5.2,27.0,11.0,326.0,416.0,637.0,3855.0,24.0,16.0,5.7,204.0,340.0,1463.0,11.0,4.3,88.0,78.0,625.0,34.0,34.1,14.5,-25.01
2,3,Buffalo Bills,16,456.0,6069.0,1064.0,5.7,22.0,6.0,373.0,390.0,609.0,4030.0,34.0,16.0,6.3,221.0,428.0,2039.0,19.0,4.8,127.0,109.0,940.0,25.0,45.9,12.2,142.89,2021,2,16.0,279.0,4584.0,968.0,4.7,30.0,11.0,281.0,290.0,510.0,2766.0,11.0,19.0,5.1,135.0,425.0,1818.0,19.0,4.3,107.0,98.0,817.0,39.0,28.9,15.6,55.21
3,4,Kansas City Chiefs,16,452.0,6356.0,1060.0,6,25.0,12.0,391.0,421.0,631.0,4536.0,35.0,13.0,6.9,248.0,402.0,1820.0,16.0,4.5,113.0,106.0,880.0,30.0,48.1,14.4,183.83,2021,13,16.0,340.0,5908.0,1006.0,5.9,28.0,13.0,345.0,388.0,585.0,4100.0,27.0,15.0,6.7,200.0,391.0,1808.0,12.0,4.6,113.0,110.0,866.0,32.0,36.6,16.1,-95.51
4,5,Cincinnati Bengals,16,444.0,5963.0,995.0,6,21.0,7.0,326.0,369.0,526.0,4300.0,35.0,14.0,7.5,204.0,418.0,1663.0,16.0,4,90.0,68.0,588.0,32.0,43.6,10.5,119.1,2021,18,16.0,355.0,5588.0,1009.0,5.5,19.0,7.0,315.0,403.0,602.0,4051.0,24.0,12.0,6.3,205.0,366.0,1537.0,14.0,4.2,92.0,112.0,900.0,18.0,34.3,10.7,-27.17

In [29]:
columns = ['O_Games_Played', 'O_Points_For', 'O_Total_Yards',
       'O_Plays', 'O_Y/Play', 'O_TO', 'O_Fumbles_Lost', 'O_1st_D',
       'O_P_Completions', 'O_P_Attempts', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Att', 'O_R_Yards', 'O_R_TD',
       'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 'O_Pe_1st_D',
       'O_Scoring_Drives', 'O_TO_%', 'O_Expected_Points', 
       'D_Games_Played', 'D_Points_Allowed', 'D_Total_Yards', 'D_Plays',
       'D_Y/Play', 'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Attempts', 'D_P_Yards', 'D_P_TD', 'D_P_Int', 'D_P_Y/PA',
       'D_P_Passing_1st_D', 'D_R_Att', 'D_R_Yards', 'D_R_TD', 'D_R_Y/A',
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Pe_1st_D', 'D_Scoring_Drives',
       'D_TD_%', 'D_Expected_Points']

for col in [columns]:
    mydata[col] = mydata[col].astype('float')

### Append Superbowl Winners

In [30]:
mydata['Superbowl'] = 0

In [31]:
sbwinners = pd.read_csv('./resources/SuperbowlWinners.csv')
sbwinners.drop(columns=['Unnamed: 0'], inplace=True)

In [32]:
sbwinners.head()

,Date,SB,Winner,Pts,Loser,Pts.1,MVP,Stadium,City,State
0,Feb 3 2019,LIII (53),New England Patriots,13,Los Angeles Rams,3,Julian Edelman,Mercedez-Benz Stadium,Atlanta,Georgia
1,Feb 4 2018,LII (52),Philadelphia Eagles,41,New England Patriots,33,Nick Foles,U.S. Bank Stadium,Minneapolis,Minnesota
2,Feb 5 2017,LI (51),New England Patriots,34,Atlanta Falcons,28,Tom Brady,NRG Stadium,Houston,Texas
3,Feb 7 2016,50,Denver Broncos,24,Carolina Panthers,10,Von Miller,Levi's Stadium,Santa Clara,California
4,Feb 1 2015,XLIX (49),New England Patriots,28,Seattle Seahawks,24,Tom Brady,University of Phoenix Stadium,Glendale,Arizona

In [33]:
sbwinners.Date = pd.to_datetime(sbwinners.Date)

In [34]:
sbwinners['Year'] = pd.DatetimeIndex(sbwinners['Date']).year
sbwinners = sbwinners[['Year', 'Winner']]
sbwinners.head()

   Year                Winner
0  2019  New England Patriots
1  2018   Philadelphia Eagles
2  2017  New England Patriots
3  2016        Denver Broncos
4  2015  New England Patriots

In [35]:
sbwinners['Year'] = sbwinners['Year'] - 1
sbwinners.Year = sbwinners.Year.astype('object')
sbwinners['Superbowl'] = 1

In [36]:
sbwinners.Year = sbwinners.Year.astype('int')
mydata.Year = mydata.Year.astype('int')

test = pd.merge(mydata, sbwinners, left_on = ['Year', 'Team'], right_on = ['Year', 'Winner'], how = 'left')
test.tail()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Superbowl_x,Winner,Superbowl_y
66,3,Philadelphia Eagles,16.0,457.0,5852.0,1073.0,5.5,20.0,11.0,338.0,341.0,564.0,3737.0,38.0,9.0,6.2,193.0,473.0,2115.0,9.0,4.5,108.0,116.0,962.0,37.0,40.3,9.4,21.06,2017,4,16.0,295.0,4904.0,976.0,5.0,31.0,12.0,272.0,363.0,601.0,3637.0,24.0,19.0,5.7,177.0,337.0,1267.0,7.0,3.8,62.0,101.0,917.0,33.0,27.1,15.4,162.09,0,Philadelphia Eagles,1.0
67,5,Jacksonville Jaguars,16.0,417.0,5855.0,1078.0,5.4,23.0,10.0,332.0,316.0,527.0,3593.0,21.0,13.0,6.5,193.0,527.0,2262.0,18.0,4.3,101.0,112.0,936.0,38.0,34.7,11.1,-36.01,2017,2,16.0,268.0,4578.0,993.0,4.6,33.0,12.0,257.0,289.0,509.0,2718.0,17.0,21.0,4.8,143.0,429.0,1860.0,9.0,4.3,91.0,112.0,1050.0,23.0,23.9,15.6,252.15,0,NaN,NaN
68,3,New England Patriots,16.0,441.0,6180.0,1056.0,5.9,11.0,9.0,351.0,368.0,550.0,4308.0,32.0,2.0,7.5,203.0,482.0,1872.0,19.0,3.9,109.0,93.0,819.0,39.0,42.9,4.9,113.38,2016,1,16.0,250.0,5223.0,998.0,5.2,23.0,10.0,294.0,368.0,596.0,3806.0,21.0,13.0,6.0,190.0,368.0,1417.0,6.0,3.9,81.0,113.0,930.0,23.0,26.8,11.2,108.15,0,New England Patriots,1.0
69,5,Dallas Cowboys,16.0,421.0,6027.0,1010.0,6.0,15.0,9.0,358.0,325.0,483.0,3631.0,25.0,6.0,7.1,191.0,499.0,2396.0,24.0,4.8,142.0,105.0,879.0,25.0,43.9,8.7,86.30,2016,5,16.0,306.0,5503.0,1009.0,5.5,20.0,11.0,330.0,425.0,633.0,4167.0,25.0,9.0,6.2,226.0,340.0,1336.0,9.0,3.9,79.0,90.0,784.0,25.0,35.1,11.3,-27.42,0,NaN,NaN
70,4,Seattle Seahawks,16.0,423.0,6058.0,1035.0,5.9,16.0,8.0,335.0,333.0,489.0,3790.0,34.0,8.0,7.1,190.0,500.0,2268.0,10.0,4.5,128.0,117.0,1007.0,17.0,42.0,8.6,129.31,2015,1,16.0,277.0,4668.0,947.0,4.9,23.0,9.0,273.0,333.0,548.0,3364.0,14.0,14.0,5.8,175.0,362.0,1304.0,10.0,3.6,71.0,94.0,795.0,27.0,29.3,13.2,59.08,0,NaN,NaN

In [37]:
test.drop(['Superbowl_x', 'Winner'], axis=1, inplace = True)

In [38]:
pd.set_option('display.max_rows', 500)
test.Superbowl_y = test.Superbowl_y.fillna(0)
test.Superbowl_y = test.Superbowl_y.astype('int')
test.rename(columns = {'Superbowl_y': 'Superbowl'}, inplace = True)

In [39]:
test.dtypes
test.Superbowl.sum()

2

### Modeling

In [40]:
import pylab as pl
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [41]:
test.head()

,O_Rank,Team,O_Games_Played,O_Points_For,O_Total_Yards,O_Plays,O_Y/Play,O_TO,O_Fumbles_Lost,O_1st_D,O_P_Completions,O_P_Attempts,O_P_Yards,O_P_TD,O_P_Int,O_P_Y/PA,O_P_Passing_1st_D,O_R_Att,O_R_Yards,O_R_TD,O_R_Y/A,O_R_1st_D,O_Pe,O_Pe_Yards,O_Pe_1st_D,O_Scoring_Drives,O_TO_%,O_Expected_Points,Year,D_Rank,D_Games_Played,D_Points_Allowed,D_Total_Yards,D_Plays,D_Y/Play,D_TD,D_Fumbles_Lost,D_1st_D,D_P_Completions,D_P_Attempts,D_P_Yards,D_P_TD,D_P_Int,D_P_Y/PA,D_P_Passing_1st_D,D_R_Att,D_R_Yards,D_R_TD,D_R_Y/A,D_R_1st_D,D_Pe,D_Pe_Yards,D_Pe_1st_D,D_Scoring_Drives,D_TD_%,D_Expected_Points,Superbowl
0,1,Dallas Cowboys,16.0,479.0,6444.0,1092.0,5.9,20.0,9.0,368.0,422.0,619.0,4496.0,35.0,11.0,6.9,235.0,441.0,1948.0,13.0,4.4,102.0,122.0,1059.0,31.0,41.8,10.4,129.50,2021,7,16.0,332.0,5652.0,1012.0,5.6,33.0,8.0,305.0,344.0,578.0,3883.0,22.0,25.0,6.3,180.0,396.0,1769.0,12.0,4.5,90.0,118.0,943.0,35.0,31.6,17.1,31.06,0
1,2,Tampa Bay Buccaneers,16.0,470.0,6492.0,1079.0,6.0,19.0,7.0,383.0,463.0,692.0,4905.0,40.0,12.0,6.9,258.0,365.0,1587.0,16.0,4.3,100.0,95.0,864.0,25.0,43.4,10.4,194.61,2021,10,16.0,336.0,5318.0,1022.0,5.2,27.0,11.0,326.0,416.0,637.0,3855.0,24.0,16.0,5.7,204.0,340.0,1463.0,11.0,4.3,88.0,78.0,625.0,34.0,34.1,14.5,-25.01,0
2,3,Buffalo Bills,16.0,456.0,6069.0,1064.0,5.7,22.0,6.0,373.0,390.0,609.0,4030.0,34.0,16.0,6.3,221.0,428.0,2039.0,19.0,4.8,127.0,109.0,940.0,25.0,45.9,12.2,142.89,2021,2,16.0,279.0,4584.0,968.0,4.7,30.0,11.0,281.0,290.0,510.0,2766.0,11.0,19.0,5.1,135.0,425.0,1818.0,19.0,4.3,107.0,98.0,817.0,39.0,28.9,15.6,55.21,0
3,4,Kansas City Chiefs,16.0,452.0,6356.0,1060.0,6.0,25.0,12.0,391.0,421.0,631.0,4536.0,35.0,13.0,6.9,248.0,402.0,1820.0,16.0,4.5,113.0,106.0,880.0,30.0,48.1,14.4,183.83,2021,13,16.0,340.0,5908.0,1006.0,5.9,28.0,13.0,345.0,388.0,585.0,4100.0,27.0,15.0,6.7,200.0,391.0,1808.0,12.0,4.6,113.0,110.0,866.0,32.0,36.6,16.1,-95.51,0
4,5,Cincinnati Bengals,16.0,444.0,5963.0,995.0,6.0,21.0,7.0,326.0,369.0,526.0,4300.0,35.0,14.0,7.5,204.0,418.0,1663.0,16.0,4.0,90.0,68.0,588.0,32.0,43.6,10.5,119.10,2021,18,16.0,355.0,5588.0,1009.0,5.5,19.0,7.0,315.0,403.0,602.0,4051.0,24.0,12.0,6.3,205.0,366.0,1537.0,14.0,4.2,92.0,112.0,900.0,18.0,34.3,10.7,-27.17,0

In [42]:
#split into values for test and train
test.O_Rank = test.O_Rank.astype('int')
test.D_Rank = test.D_Rank.astype('int')

train_columns = ['O_Rank', 'O_Points_For', 'O_Total_Yards',
       'O_Y/Play', 'O_TO', 'O_1st_D',
       'O_P_Completions', 'O_P_Yards', 'O_P_TD', 'O_P_Int',
       'O_P_Y/PA', 'O_P_Passing_1st_D', 'O_R_Yards', 'O_R_TD',
       'O_R_Y/A', 'O_R_1st_D', 'O_Pe', 'O_Pe_Yards', 
       'O_Scoring_Drives', 'D_Rank',
       'D_Points_Allowed', 'D_Total_Yards', 
       'D_Y/Play', 'D_TD', 'D_Fumbles_Lost', 'D_1st_D', 'D_P_Completions',
       'D_P_Yards', 'D_P_TD', 'D_P_Int', 'D_P_Y/PA',
       'D_P_Passing_1st_D', 'D_R_Yards', 'D_R_TD', 'D_R_Y/A',
       'D_R_1st_D', 'D_Pe', 'D_Pe_Yards', 'D_Scoring_Drives']


X = np.asarray(test[train_columns])
y = np.asarray(test['Superbowl'])
print(X.shape)
print(y.shape)

(71, 39)
(71,)

In [43]:
#normalize
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [44]:
teams = test.loc[ :31 , 'Team']

o_rank = test.loc[0:31, 'O_Rank']
d_rank = test.loc[0:31, 'D_Rank']

X_test = X[0:32]
X_train = X[32:]

y_test = y[0:32]
y_train = y[32:]

print(X_test.shape)
print(y_test.shape)
print(X_train.shape)
print(y_train.shape)

(32, 39)
(32,)
(39, 39)
(39,)

## Logistic Regression

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [46]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [47]:
yhat = LR.predict(X_test)
yhat

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [48]:
yhat_binary = LR.predict(X_train)
print("Accuracy:",metrics.accuracy_score(y_train, yhat_binary))

Accuracy: 0.8717948717948718

In [49]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

np.vstack((y_train, yhat_binary)).T

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 1]])

In [50]:
# Abovev 50% is 1

df = pd.DataFrame({'Team':teams, 'Prediction':yhat}) 
df

                        Team  Prediction
0             Dallas Cowboys           1
1       Tampa Bay Buccaneers           0
2              Buffalo Bills           1
3         Kansas City Chiefs           0
4         Cincinnati Bengals           0
5       Los Angeles Chargers           0
6         Indianapolis Colts           0
7       New England Patriots           1
8           Los Angeles Rams           0
9          Green Bay Packers           0
10         Arizona Cardinals           0
11       Philadelphia Eagles           0
12       San Francisco 49ers           0
13         Minnesota Vikings           0
14          Tennessee Titans           1
15          Baltimore Ravens           0
16          Seattle Seahawks           0
17         Las Vegas Raiders           1
18        New Orleans Saints           1
19          Cleveland Browns           1
20       Pittsburgh Steelers           1
21  Washington Football Team           0
22            Denver Broncos           1
23            Miami Dolphins           1
24             New York Jets           0
25             Chicago Bears           1
26           Atlanta Falcons           1
27             Detroit Lions           0
28         Carolina Panthers           1
29            Houston Texans           1
30           New York Giants           1
31      Jacksonville Jaguars           1

In [51]:
#Probability
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.48573193, 0.51426807],
       [0.58695119, 0.41304881],
       [0.49508204, 0.50491796],
       [0.58411889, 0.41588111],
       [0.53035254, 0.46964746],
       [0.60425458, 0.39574542],
       [0.55963901, 0.44036099],
       [0.49611934, 0.50388066],
       [0.55896721, 0.44103279],
       [0.5587709 , 0.4412291 ],
       [0.52319816, 0.47680184],
       [0.5395529 , 0.4604471 ],
       [0.51824656, 0.48175344],
       [0.54900694, 0.45099306],
       [0.46900396, 0.53099604],
       [0.56404277, 0.43595723],
       [0.51240059, 0.48759941],
       [0.49350124, 0.50649876],
       [0.42038774, 0.57961226],
       [0.48459066, 0.51540934],
       [0.4572104 , 0.5427896 ],
       [0.54731327, 0.45268673],
       [0.45703559, 0.54296441],
       [0.43629673, 0.56370327],
       [0.58149469, 0.41850531],
       [0.47135233, 0.52864767],
       [0.48791143, 0.51208857],
       [0.53790154, 0.46209846],
       [0.41604381, 0.58395619],
       [0.46214172, 0.53785828],
       [0.4736943 , 0.5263057 ],
       [0.48542126, 0.51457874]])

In [52]:
# O and D rank

df2 = pd.DataFrame({'Team':teams, 'Prediction':yhat_prob[:,1], 'O_Rank':o_rank, 'D_rank':d_rank }) 
df2

                        Team  Prediction  O_Rank  D_rank
0             Dallas Cowboys    0.514268       1       7
1       Tampa Bay Buccaneers    0.413049       2      10
2              Buffalo Bills    0.504918       3       2
3         Kansas City Chiefs    0.415881       4      13
4         Cincinnati Bengals    0.469647       5      18
5       Los Angeles Chargers    0.395745       6      26
6         Indianapolis Colts    0.440361       7      12
7       New England Patriots    0.503881       8       1
8           Los Angeles Rams    0.441033       9      15
9          Green Bay Packers    0.441229      10       9
10         Arizona Cardinals    0.476802      11       5
11       Philadelphia Eagles    0.460447      12       8
12       San Francisco 49ers    0.481753      13      14
13         Minnesota Vikings    0.450993      14      25
14          Tennessee Titans    0.530996      15       6
15          Baltimore Ravens    0.435957      16      20
16          Seattle Seahawks    0.487599      17      11
17         Las Vegas Raiders    0.506499      18      24
18        New Orleans Saints    0.579612      19       4
19          Cleveland Browns    0.515409      20      17
20       Pittsburgh Steelers    0.542790      21      22
21  Washington Football Team    0.452687      22      28
22            Denver Broncos    0.542964      23       3
23            Miami Dolphins    0.563703      24      16
24             New York Jets    0.418505      25      32
25             Chicago Bears    0.528648      26      21
26           Atlanta Falcons    0.512089      27      29
27             Detroit Lions    0.462098      28      30
28         Carolina Panthers    0.583956      29      19
29            Houston Texans    0.537858      30      27
30           New York Giants    0.526306      31      23
31      Jacksonville Jaguars    0.514579      32      31

In [53]:
# Add the prediction rank

df2 = df2.sort_values(by = ['Prediction'], ascending = False)
df2['Prediction_Rank'] = df2['Prediction'].rank(ascending = False)

df2

                        Team  Prediction  O_Rank  D_rank  Prediction_Rank
28         Carolina Panthers    0.583956      29      19              1.0
18        New Orleans Saints    0.579612      19       4              2.0
23            Miami Dolphins    0.563703      24      16              3.0
22            Denver Broncos    0.542964      23       3              4.0
20       Pittsburgh Steelers    0.542790      21      22              5.0
29            Houston Texans    0.537858      30      27              6.0
14          Tennessee Titans    0.530996      15       6              7.0
25             Chicago Bears    0.528648      26      21              8.0
30           New York Giants    0.526306      31      23              9.0
19          Cleveland Browns    0.515409      20      17             10.0
31      Jacksonville Jaguars    0.514579      32      31             11.0
0             Dallas Cowboys    0.514268       1       7             12.0
26           Atlanta Falcons    0.512089      27      29             13.0
17         Las Vegas Raiders    0.506499      18      24             14.0
2              Buffalo Bills    0.504918       3       2             15.0
7       New England Patriots    0.503881       8       1             16.0
16          Seattle Seahawks    0.487599      17      11             17.0
12       San Francisco 49ers    0.481753      13      14             18.0
10         Arizona Cardinals    0.476802      11       5             19.0
4         Cincinnati Bengals    0.469647       5      18             20.0
27             Detroit Lions    0.462098      28      30             21.0
11       Philadelphia Eagles    0.460447      12       8             22.0
21  Washington Football Team    0.452687      22      28             23.0
13         Minnesota Vikings    0.450993      14      25             24.0
9          Green Bay Packers    0.441229      10       9             25.0
8           Los Angeles Rams    0.441033       9      15             26.0
6         Indianapolis Colts    0.440361       7      12             27.0
15          Baltimore Ravens    0.435957      16      20             28.0
24             New York Jets    0.418505      25      32             29.0
3         Kansas City Chiefs    0.415881       4      13             30.0
1       Tampa Bay Buccaneers    0.413049       2      10             31.0
5       Los Angeles Chargers    0.395745       6      26             32.0

## ADABOOST

In [54]:
# Load libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.ensemble import AdaBoostClassifier

# Import Support Vector Classifier
from sklearn.svm import SVC
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [55]:
svc=SVC(probability=True, kernel='linear')

# Create adaboost classifer object
ada =AdaBoostClassifier(n_estimators=20, base_estimator=svc,learning_rate=1)

#abc = AdaBoostClassifier(n_estimators=30, learning_rate=1)

# Train Adaboost Classifer
model = ada.fit(X_train, y_train)

In [56]:
#Predict the response for test dataset
y_pred_binary = model.predict(X_train)
y_pred = model.predict_proba(X_test)
y_pred

array([[0.92769765, 0.07230235],
       [0.93582542, 0.06417458],
       [0.9383111 , 0.0616889 ],
       [0.93804417, 0.06195583],
       [0.93692015, 0.06307985],
       [0.94965993, 0.05034007],
       [0.93498536, 0.06501464],
       [0.93642874, 0.06357126],
       [0.94224104, 0.05775896],
       [0.93791066, 0.06208934],
       [0.93441687, 0.06558313],
       [0.94282638, 0.05717362],
       [0.94010545, 0.05989455],
       [0.94325934, 0.05674066],
       [0.93669207, 0.06330793],
       [0.9422749 , 0.0577251 ],
       [0.93970199, 0.06029801],
       [0.94379614, 0.05620386],
       [0.93454011, 0.06545989],
       [0.9427908 , 0.0572092 ],
       [0.94250088, 0.05749912],
       [0.94726801, 0.05273199],
       [0.93665123, 0.06334877],
       [0.9383329 , 0.0616671 ],
       [0.95883632, 0.04116368],
       [0.94926326, 0.05073674],
       [0.94677489, 0.05322511],
       [0.95304702, 0.04695298],
       [0.94505119, 0.05494881],
       [0.95075369, 0.04924631],
       [0.94711915, 0.05288085],
       [0.95584931, 0.04415069]])

In [62]:
df3 = pd.DataFrame({'Team':teams, 'Prediction':y_pred[:,1], 'O_Rank':o_rank, 'D_rank':d_rank }) 
df3['Prediction_Rank'] = df3['Prediction'].rank(ascending = False)
df3 = df3.sort_values(by = ['Prediction'], ascending = False)
df3

                        Team  Prediction  O_Rank  D_rank  Prediction_Rank
0             Dallas Cowboys    0.072302       1       7              1.0
10         Arizona Cardinals    0.065583      11       5              2.0
18        New Orleans Saints    0.065460      19       4              3.0
6         Indianapolis Colts    0.065015       7      12              4.0
1       Tampa Bay Buccaneers    0.064175       2      10              5.0
7       New England Patriots    0.063571       8       1              6.0
22            Denver Broncos    0.063349      23       3              7.0
14          Tennessee Titans    0.063308      15       6              8.0
4         Cincinnati Bengals    0.063080       5      18              9.0
9          Green Bay Packers    0.062089      10       9             10.0
3         Kansas City Chiefs    0.061956       4      13             11.0
2              Buffalo Bills    0.061689       3       2             12.0
23            Miami Dolphins    0.061667      24      16             13.0
16          Seattle Seahawks    0.060298      17      11             14.0
12       San Francisco 49ers    0.059895      13      14             15.0
8           Los Angeles Rams    0.057759       9      15             16.0
15          Baltimore Ravens    0.057725      16      20             17.0
20       Pittsburgh Steelers    0.057499      21      22             18.0
19          Cleveland Browns    0.057209      20      17             19.0
11       Philadelphia Eagles    0.057174      12       8             20.0
13         Minnesota Vikings    0.056741      14      25             21.0
17         Las Vegas Raiders    0.056204      18      24             22.0
28         Carolina Panthers    0.054949      29      19             23.0
26           Atlanta Falcons    0.053225      27      29             24.0
30           New York Giants    0.052881      31      23             25.0
21  Washington Football Team    0.052732      22      28             26.0
25             Chicago Bears    0.050737      26      21             27.0
5       Los Angeles Chargers    0.050340       6      26             28.0
29            Houston Texans    0.049246      30      27             29.0
27             Detroit Lions    0.046953      28      30             30.0
31      Jacksonville Jaguars    0.044151      32      31             31.0
24             New York Jets    0.041164      25      32             32.0

In [63]:
print("Accuracy:",metrics.accuracy_score(y_train, y_pred_binary))

Accuracy: 0.9487179487179487

### PCA Testing

In [ ]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas
from path import Path
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
# Load the data into a Pandas DataFrame
df_market_data = pd.read_csv(
    Path("Resources/crypto_market_data.csv"),
    index_col="coin_id")

# Display sample data
df_market_data.head(10)

In [ ]:
# Generate summary statistics
df_market_data.describe()

In [ ]:
# Generate summary statistics
df_market_data.describe()

In [ ]:
### Prepare the Data

This section prepares the data before running the K-Means algorithm. It follows these steps:

1. Use the `StandardScaler` module from scikit-learn to normalize the CSV file data. This will require you to utilize the `fit_transform` function.

2. Create a DataFrame that contains the scaled data. Be sure to set the `coin_id` index from the original DataFrame as the index for the new DataFrame. Review the resulting DataFrame.

In [ ]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
scaled_data = StandardScaler().fit_transform(df_market_data)

In [ ]:
# Create a DataFrame with the scaled data
df_market_data_scaled = pd.DataFrame(
    scaled_data,
    columns=df_market_data.columns
)

# Copy the crypto names from the original data
df_market_data_scaled["coin_id"] = df_market_data.index

# Set the coinid column as index
df_market_data_scaled = df_market_data_scaled.set_index("coin_id")

# Display sample data
df_market_data_scaled.head()

In [ ]:
### Fnd the K Means

In [ ]:
# Create a list with the number of k-values to try
k = list(range(1,11))

In [ ]:
# Create an empy list to store the inertia values
inertia =[]

In [ ]:
# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_scaled`
# 3. Append the model.inertia_ to the inertia list
for i in k:
    model = KMeans(n_clusters=i, random_state=0)
    model.fit(df_market_data_scaled)
    inertia.append(model.inertia_)

In [ ]:
# Create a dictionary with the data to plot the Elbow curve
elbow_data = {
    "k": k,
    "inertia": inertia
}
# Create a DataFrame with the data to plot the Elbow curve
df_elbow = pd.DataFrame(elbow_data)

In [ ]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.
elbow = df_elbow.hvplot.line(x="k", y="inertia", title="Elbow Curve", xticks=k)

In [ ]:
# Initialize the K-Means model using the best value for 
model = KMeans(n_clusters=4)

In [ ]:
# Fit the K-Means model using the scaled data
model.fit(df_market_data_scaled)

In [ ]:
# Predict the clusters to group the cryptocurrencies using the scaled data
market_clusters = model.predict(df_market_data_scaled)

# View the resulting array of cluster values.
print(market_clusters)

In [ ]:
# Create a copy of the DataFrame
df_market_data_predictions = df_market_data_scaled.copy()

In [ ]:
# Create a scatter plot using hvPlot by setting 
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.
market_data_predictions = df_market_data_predictions.hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by=("market_clusters"),
    hover_cols = ["coin_id"], 
    title = "Scatter Plot by Price Change - k=4"
)

In [ ]:
# Create a PCA model instance and set `n_components=3`.
pca =PCA(n_components=3)

In [ ]:
# Use the PCA model with `fit_transform` to reduce to 
# three principal components.
market_data_pca = pca.fit_transform(df_market_data_scaled)

# View the first five rows of the DataFrame. 
print(market_data_pca[:5])

In [ ]:
# Retrieve the explained variance to determine how much information 
# can be attributed to each principal component.
print(pca.explained_variance_ratio_)

In [ ]:
# Create a new DataFrame with the PCA data.
# Note: The code for this step is provided for you

# Creating a DataFrame with the PCA data
df_market_data_pca = pd.DataFrame(market_data_pca, columns=["PC1", "PC2", "PC3"])

# Copy the crypto names from the original data
df_market_data_pca["coin_id"] = df_market_data.index

# Set the coinid column as index
df_market_data_pca = df_market_data_pca.set_index("coin_id")

# Display sample data
df_market_data_pca.head()