In [19]:

import pandas as pd

In [33]:
url = "http://pfref.com/pi/share/YNNiB"

In [34]:
df = pd.read_html(url, header = 0)
df = df[0]

In [35]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Scor,Scor.1,Offe,Offe.1,...,Offe.3,Offe.4,Defe,Defe.1,Defe.2,Defe.3,Defe.4,Expe,Expe.1,Expe.2
0,Week,Date,NaN,Rec,NaN,Opp,Tm,Opp,1stD,TotYd,...,RushY,TO,1stD,TotYd,PassY,RushY,TO,Offense,Defense,Sp. Tms
1,1,September 12,W,1-0,@,Buffalo Bills,23,16,16,252,...,75,NaN,22,371,254,117,1,-0.54,3.55,5.01
2,2,September 19,L,1-1,NaN,Las Vegas Raiders,17,26,17,331,...,39,1,22,425,373,52,NaN,1.19,-12.75,0.99
3,3,September 26,L,1-2,NaN,Cincinnati Bengals,10,24,21,342,...,45,2,12,268,172,96,1,-8.46,-0.17,-6.09
4,4,October 3,L,1-3,@,Green Bay Packers,17,27,17,282,...,62,2,23,367,236,131,1,-5.05,-7.14,3.23

In [36]:
df.to_csv('./resources/Pittsburgh_Steelers.csv', index=False)