In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
%matplotlib inline

In [2]:
# read csv files for each playoff teams
bills = pd.read_csv(Path("resources/Buf_Bills2021.csv"), header=1)
rams = pd.read_csv(Path("resources/LA_Rams2021.csv"), header=1)
bengals = pd.read_csv(Path("resources/Cin_Bengals.csv"), header=1)
chiefs = pd.read_csv(Path("resources/KC_Chiefs2021.csv"), header=1)
cowboys = pd.read_csv(Path("resources/Dallas_Cowboys2021.csv"), header=1)
titans = pd.read_csv(Path("resources/Ten_Titans.csv"), header=1)
packers = pd.read_csv(Path("resources/GB_Packers2021.csv"), header=1)
buccaneers = pd.read_csv(Path("resources/Tampa_Buccaneers2021.csv"), header=1)
cardinals = pd.read_csv(Path("resources/Arizona_Cardinals.csv"), header=1)
patriots = pd.read_csv(Path("resources/NE_Patriots.csv"), header=1)
eagles = pd.read_csv(Path("resources/Philadelphia_Eagles.csv"), header=1)

rams.head()

,Week,Date,Unnamed: 2,Rec,Unnamed: 4,Opp,Tm,Opp.1,1stD,TotYd,...,RushY,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense,Defense,Sp. Tms
0,1,September 12,W,1-0,NaN,Chicago Bears,34.0,14.0,18.0,386.0,...,74.0,NaN,24.0,322.0,188.0,134.0,2.0,21.58,0.85,-0.52
1,2,September 19,W,2-0,@,Indianapolis Colts,27.0,24.0,21.0,371.0,...,101.0,2.0,22.0,354.0,245.0,109.0,2.0,7.11,-1.29,-3.09
2,3,September 26,W,3-0,NaN,Tampa Bay Buccaneers,34.0,24.0,22.0,407.0,...,76.0,NaN,27.0,446.0,411.0,35.0,NaN,20.56,-15.15,3.43
3,4,October 3,L,3-1,NaN,Arizona Cardinals,20.0,37.0,24.0,401.0,...,121.0,2.0,27.0,465.0,249.0,216.0,NaN,8.94,-21.72,-2.64
4,5,October 7,W,4-1,@,Seattle Seahawks,26.0,17.0,24.0,476.0,...,118.0,1.0,22.0,354.0,262.0,92.0,2.0,13.76,-6.71,-0.05

In [3]:
bills = bills[0:16].drop(columns=['Date'])
rams = rams[0:16].drop(columns=['Date'])
bengals = bengals[0:16].drop(columns=['Date'])
chiefs = chiefs[0:16].drop(columns=['Date'])
cowboys = cowboys[0:16].drop(columns=['Date'])
titans = titans[0:16].drop(columns=['Date'])
packers = packers[0:16].drop(columns=['Date'])
buccaneers = buccaneers[0:16].drop(columns=['Date'])
cardinals = cardinals[0:16].drop(columns=['Date'])
patriots = patriots[0:16].drop(columns=['Date'])
eagles = eagles[0:16].drop(columns=['Date'])

In [4]:
bills.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
rams.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
bengals.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
chiefs.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
cowboys.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
titans.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
packers.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
buccaneers.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
cardinals.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
patriots.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
eagles.columns = ['Week','Result','Rec','Home','Opp','TmScore','OppScore',
                      'O_1stD','O_Tot_yd','O_P_Yd','O_R_Yd','O_TO',
                 'D_1stD','D_Tot_Yd','D_P_Yd','D_R_Yd','D_TO','Offence','Defense','Sp.Tms']
eagles

,Week,Result,Rec,Home,Opp,TmScore,OppScore,O_1stD,O_Tot_yd,O_P_Yd,O_R_Yd,O_TO,D_1stD,D_Tot_Yd,D_P_Yd,D_R_Yd,D_TO,Offence,Defense,Sp.Tms
0,1,W,1-0,@,Atlanta Falcons,32.0,6.0,24.0,434.0,261.0,173.0,NaN,19.0,260.0,136.0,124.0,NaN,13.14,12.48,-2.36
1,2,L,1-1,NaN,San Francisco 49ers,11.0,17.0,18.0,328.0,177.0,151.0,NaN,23.0,306.0,189.0,117.0,NaN,5.30,-7.86,-2.68
2,3,L,1-2,@,Dallas Cowboys,21.0,41.0,12.0,367.0,303.0,64.0,2.0,27.0,380.0,220.0,160.0,1.0,-11.19,-9.13,0.01
3,4,L,1-3,NaN,Kansas City Chiefs,30.0,42.0,30.0,461.0,358.0,103.0,NaN,31.0,471.0,271.0,200.0,1.0,21.32,-34.67,0.70
4,5,W,2-3,@,Carolina Panthers,21.0,18.0,15.0,273.0,182.0,91.0,2.0,17.0,267.0,158.0,109.0,3.0,-15.13,16.27,3.99
5,6,L,2-4,NaN,Tampa Bay Buccaneers,22.0,28.0,16.0,213.0,113.0,100.0,1.0,27.0,399.0,297.0,102.0,1.0,9.52,-15.69,-3.01
6,7,L,2-5,@,Las Vegas Raiders,22.0,33.0,22.0,358.0,223.0,135.0,2.0,23.0,442.0,323.0,119.0,1.0,4.67,-18.00,-1.38
7,8,W,3-5,@,Detroit Lions,44.0,6.0,27.0,350.0,114.0,236.0,NaN,15.0,228.0,171.0,57.0,1.0,18.70,17.40,1.69
8,9,L,3-6,NaN,Los Angeles Chargers,24.0,27.0,20.0,331.0,155.0,176.0,NaN,28.0,445.0,356.0,89.0,NaN,17.56,-20.72,1.49
9,10,W,4-6,@,Denver Broncos,30.0,13.0,22.0,386.0,170.0,216.0,1.0,17.0,308.0,212.0,96.0,1.0,8.45,6.62,-0.91
10,11,W,5-6,NaN,New Orleans Saints,40.0,29.0,21.0,380.0,138.0,242.0,1.0,18.0,323.0,214.0,109.0,3.0,0.60,9.01,4.11
11,12,L,5-7,@,New York Giants,7.0,13.0,19.0,332.0,124.0,208.0,4.0,17.0,264.0,194.0,70.0,NaN,-9.73,0.39,3.28
12,13,W,6-7,@,New York Jets,33.0,18.0,26.0,418.0,233.0,185.0,NaN,21.0,281.0,211.0,70.0,1.0,22.38,-6.13,-1.78
13,15,W,7-7,NaN,Washington Football Team,27.0,17.0,23.0,519.0,281.0,238.0,2.0,14.0,237.0,174.0,63.0,NaN,13.15,0.64,-5.36
14,16,W,8-7,NaN,New York Giants,34.0,10.0,17.0,324.0,194.0,130.0,NaN,15.0,192.0,108.0,84.0,2.0,4.97,17.66,-0.73
15,17,W,9-7,@,Washington Football Team,20.0,16.0,18.0,330.0,212.0,118.0,NaN,24.0,312.0,218.0,94.0,1.0,9.44,-2.61,-2.02

In [5]:
bills.insert(0,"Team",'Bills')
rams.insert(0,"Team",'Rams')
bengals.insert(0,"Team",'Bengals')
chiefs.insert(0,"Team",'Chiefs')
cowboys.insert(0,"Team",'Cowboys')
titans.insert(0,"Team",'Titans')
packers.insert(0,"Team",'Packers')
buccaneers.insert(0,"Team",'Buccaneers')
cardinals.insert(0,"Team",'Cardinals')
patriots.insert(0,"Team",'Patriots')
eagles.insert(0,"Team",'Eagles')

rams

,Team,Week,Result,Rec,Home,Opp,TmScore,OppScore,O_1stD,O_Tot_yd,...,O_R_Yd,O_TO,D_1stD,D_Tot_Yd,D_P_Yd,D_R_Yd,D_TO,Offence,Defense,Sp.Tms
0,Rams,1,W,1-0,NaN,Chicago Bears,34.0,14.0,18.0,386.0,...,74.0,NaN,24.0,322.0,188.0,134.0,2.0,21.58,0.85,-0.52
1,Rams,2,W,2-0,@,Indianapolis Colts,27.0,24.0,21.0,371.0,...,101.0,2.0,22.0,354.0,245.0,109.0,2.0,7.11,-1.29,-3.09
2,Rams,3,W,3-0,NaN,Tampa Bay Buccaneers,34.0,24.0,22.0,407.0,...,76.0,NaN,27.0,446.0,411.0,35.0,NaN,20.56,-15.15,3.43
3,Rams,4,L,3-1,NaN,Arizona Cardinals,20.0,37.0,24.0,401.0,...,121.0,2.0,27.0,465.0,249.0,216.0,NaN,8.94,-21.72,-2.64
4,Rams,5,W,4-1,@,Seattle Seahawks,26.0,17.0,24.0,476.0,...,118.0,1.0,22.0,354.0,262.0,92.0,2.0,13.76,-6.71,-0.05
5,Rams,6,W,5-1,@,New York Giants,38.0,11.0,22.0,365.0,...,131.0,2.0,21.0,261.0,201.0,60.0,4.0,7.63,19.06,-0.96
6,Rams,7,W,6-1,NaN,Detroit Lions,28.0,19.0,22.0,374.0,...,47.0,NaN,19.0,415.0,278.0,137.0,2.0,20.08,-3.32,-6.99
7,Rams,8,W,7-1,@,Houston Texans,38.0,22.0,26.0,467.0,...,165.0,NaN,18.0,323.0,279.0,44.0,1.0,22.20,-1.75,-8.01
8,Rams,9,L,7-2,NaN,Tennessee Titans,16.0,28.0,22.0,347.0,...,94.0,2.0,16.0,194.0,125.0,69.0,1.0,-11.78,-1.15,-0.53
9,Rams,10,L,7-3,@,San Francisco 49ers,10.0,31.0,16.0,278.0,...,52.0,2.0,20.0,335.0,179.0,156.0,NaN,-7.18,-11.33,-0.70
10,Rams,12,L,7-4,@,Green Bay Packers,28.0,36.0,15.0,353.0,...,68.0,3.0,21.0,399.0,307.0,92.0,1.0,-5.92,-4.66,0.69
11,Rams,13,W,8-4,NaN,Jacksonville Jaguars,37.0,7.0,24.0,418.0,...,128.0,NaN,14.0,197.0,136.0,61.0,2.0,21.19,12.55,-3.25
12,Rams,14,W,9-4,@,Arizona Cardinals,30.0,23.0,18.0,356.0,...,89.0,NaN,22.0,447.0,344.0,103.0,2.0,13.49,-0.66,-3.55
13,Rams,15,W,10-4,NaN,Seattle Seahawks,20.0,10.0,20.0,332.0,...,123.0,1.0,13.0,214.0,134.0,80.0,1.0,4.19,8.13,-3.72
14,Rams,16,W,11-4,@,Minnesota Vikings,30.0,23.0,22.0,356.0,...,159.0,3.0,19.0,361.0,295.0,66.0,1.0,-0.84,1.81,7.80
15,Rams,17,W,12-4,@,Baltimore Ravens,20.0,19.0,20.0,373.0,...,73.0,3.0,19.0,327.0,162.0,165.0,2.0,2.98,-0.40,-2.65

In [6]:
Team_df = [bills, rams, bengals, chiefs, cowboys, titans, packers, buccaneers, cardinals, patriots, eagles]
total_team_df = pd.concat(Team_df)
total_team_df

,Team,Week,Result,Rec,Home,Opp,TmScore,OppScore,O_1stD,O_Tot_yd,...,O_R_Yd,O_TO,D_1stD,D_Tot_Yd,D_P_Yd,D_R_Yd,D_TO,Offence,Defense,Sp.Tms
0,Bills,1,W,1-0,NaN,Chicago Bears,34.0,14.0,18.0,386.0,...,74.0,NaN,24.0,322.0,188.0,134.0,2.0,21.58,0.85,-0.52
1,Bills,2,W,2-0,@,Indianapolis Colts,27.0,24.0,21.0,371.0,...,101.0,2.0,22.0,354.0,245.0,109.0,2.0,7.11,-1.29,-3.09
2,Bills,3,W,3-0,NaN,Tampa Bay Buccaneers,34.0,24.0,22.0,407.0,...,76.0,NaN,27.0,446.0,411.0,35.0,NaN,20.56,-15.15,3.43
3,Bills,4,L,3-1,NaN,Arizona Cardinals,20.0,37.0,24.0,401.0,...,121.0,2.0,27.0,465.0,249.0,216.0,NaN,8.94,-21.72,-2.64
4,Bills,5,W,4-1,@,Seattle Seahawks,26.0,17.0,24.0,476.0,...,118.0,1.0,22.0,354.0,262.0,92.0,2.0,13.76,-6.71,-0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,Eagles,12,L,5-7,@,New York Giants,7.0,13.0,19.0,332.0,...,208.0,4.0,17.0,264.0,194.0,70.0,NaN,-9.73,0.39,3.28
12,Eagles,13,W,6-7,@,New York Jets,33.0,18.0,26.0,418.0,...,185.0,NaN,21.0,281.0,211.0,70.0,1.0,22.38,-6.13,-1.78
13,Eagles,15,W,7-7,NaN,Washington Football Team,27.0,17.0,23.0,519.0,...,238.0,2.0,14.0,237.0,174.0,63.0,NaN,13.15,0.64,-5.36
14,Eagles,16,W,8-7,NaN,New York Giants,34.0,10.0,17.0,324.0,...,130.0,NaN,15.0,192.0,108.0,84.0,2.0,4.97,17.66,-0.73
15,Eagles,17,W,9-7,@,Washington Football Team,20.0,16.0,18.0,330.0,...,118.0,NaN,24.0,312.0,218.0,94.0,1.0,9.44,-2.61,-2.02

In [7]:
total_team_df = total_team_df.fillna(1)

In [8]:
total_team_df = total_team_df.replace('@', 0)
total_team_df.head()

,Team,Week,Result,Rec,Home,Opp,TmScore,OppScore,O_1stD,O_Tot_yd,...,O_R_Yd,O_TO,D_1stD,D_Tot_Yd,D_P_Yd,D_R_Yd,D_TO,Offence,Defense,Sp.Tms
0,Bills,1,W,1-0,1,Chicago Bears,34.0,14.0,18.0,386.0,...,74.0,1.0,24.0,322.0,188.0,134.0,2.0,21.58,0.85,-0.52
1,Bills,2,W,2-0,0,Indianapolis Colts,27.0,24.0,21.0,371.0,...,101.0,2.0,22.0,354.0,245.0,109.0,2.0,7.11,-1.29,-3.09
2,Bills,3,W,3-0,1,Tampa Bay Buccaneers,34.0,24.0,22.0,407.0,...,76.0,1.0,27.0,446.0,411.0,35.0,1.0,20.56,-15.15,3.43
3,Bills,4,L,3-1,1,Arizona Cardinals,20.0,37.0,24.0,401.0,...,121.0,2.0,27.0,465.0,249.0,216.0,1.0,8.94,-21.72,-2.64
4,Bills,5,W,4-1,0,Seattle Seahawks,26.0,17.0,24.0,476.0,...,118.0,1.0,22.0,354.0,262.0,92.0,2.0,13.76,-6.71,-0.05

In [9]:
total_team_df = total_team_df.replace('W', 1)
total_team_df = total_team_df.replace('L', 0) 
total_team_df.head()

,Team,Week,Result,Rec,Home,Opp,TmScore,OppScore,O_1stD,O_Tot_yd,...,O_R_Yd,O_TO,D_1stD,D_Tot_Yd,D_P_Yd,D_R_Yd,D_TO,Offence,Defense,Sp.Tms
0,Bills,1,1,1-0,1,Chicago Bears,34.0,14.0,18.0,386.0,...,74.0,1.0,24.0,322.0,188.0,134.0,2.0,21.58,0.85,-0.52
1,Bills,2,1,2-0,0,Indianapolis Colts,27.0,24.0,21.0,371.0,...,101.0,2.0,22.0,354.0,245.0,109.0,2.0,7.11,-1.29,-3.09
2,Bills,3,1,3-0,1,Tampa Bay Buccaneers,34.0,24.0,22.0,407.0,...,76.0,1.0,27.0,446.0,411.0,35.0,1.0,20.56,-15.15,3.43
3,Bills,4,0,3-1,1,Arizona Cardinals,20.0,37.0,24.0,401.0,...,121.0,2.0,27.0,465.0,249.0,216.0,1.0,8.94,-21.72,-2.64
4,Bills,5,1,4-1,0,Seattle Seahawks,26.0,17.0,24.0,476.0,...,118.0,1.0,22.0,354.0,262.0,92.0,2.0,13.76,-6.71,-0.05

In [10]:
total_team_df.to_csv('./resources/Team_df.csv', index=False)

In [ ]:
bills
rams
bengals
chiefs
cowboys
titans
packers
buccaneers
cardinals
patriots
eagles